apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: NAME-test-nodepool
spec:
  template:
    spec:
      requirements:
        - key: nodegroup-env
          operator: In
          values: ["NAME-test"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3a","c5a", "m5a"]
      taints:
        - key: nodegroup-env
          value: "NAME-test"
          effect: NoSchedule
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: NAME-test-nodeclass
  limits:
    cpu: 50
  disruption:
    consolidationPolicy: WhenUnderutilized
#    consolidationPolicy: WhenEmpty
#    consolidateAfter: 20s
    expireAfter: Never 

---

apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: NAME-test-nodeclass
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-zep-cluster01"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "subnet-dev"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "zep-cluster01"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 40Gi
        volumeType: gp3
        deleteOnTermination: true
        encrypted: true
  detailedMonitoring: false
