apiVersion: v1
kind: Namespace
metadata:
  name: NAME-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME-test
  namespace: NAME-test
  labels:
    app: NAME-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NAME-test
  template:
    metadata:
      labels:
        app: NAME-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodegroup-env
                    operator: In
                    values:
                      - "NAME-test"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: 
                      - "NAME-test"
              topologyKey: kubernetes.io/hostname
      tolerations:
      - effect: NoSchedule
        key: nodegroup-env
        operator: Equal
        value: "NAME-test"
